// Code generated by MockGen. DO NOT EDIT.
// Source: domain/order.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	entity "ecommerce-go-api/entity"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockOrderUsecase is a mock of OrderUsecase interface.
type MockOrderUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockOrderUsecaseMockRecorder
}

// MockOrderUsecaseMockRecorder is the mock recorder for MockOrderUsecase.
type MockOrderUsecaseMockRecorder struct {
	mock *MockOrderUsecase
}

// NewMockOrderUsecase creates a new mock instance.
func NewMockOrderUsecase(ctrl *gomock.Controller) *MockOrderUsecase {
	mock := &MockOrderUsecase{ctrl: ctrl}
	mock.recorder = &MockOrderUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderUsecase) EXPECT() *MockOrderUsecaseMockRecorder {
	return m.recorder
}

// AddItemToCart mocks base method.
func (m *MockOrderUsecase) AddItemToCart(ctx context.Context, userID uuid.UUID, req entity.AddItemToCartRequest) (*entity.CartItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItemToCart", ctx, userID, req)
	ret0, _ := ret[0].(*entity.CartItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddItemToCart indicates an expected call of AddItemToCart.
func (mr *MockOrderUsecaseMockRecorder) AddItemToCart(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItemToCart", reflect.TypeOf((*MockOrderUsecase)(nil).AddItemToCart), ctx, userID, req)
}

// AddShipment mocks base method.
func (m *MockOrderUsecase) AddShipment(ctx context.Context, userID, shopOrderID uuid.UUID, req entity.AddShipmentRequest) (*entity.ShipmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddShipment", ctx, userID, shopOrderID, req)
	ret0, _ := ret[0].(*entity.ShipmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddShipment indicates an expected call of AddShipment.
func (mr *MockOrderUsecaseMockRecorder) AddShipment(ctx, userID, shopOrderID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddShipment", reflect.TypeOf((*MockOrderUsecase)(nil).AddShipment), ctx, userID, shopOrderID, req)
}

// ApproveOrder mocks base method.
func (m *MockOrderUsecase) ApproveOrder(ctx context.Context, userID, shopOrderID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveOrder", ctx, userID, shopOrderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveOrder indicates an expected call of ApproveOrder.
func (mr *MockOrderUsecaseMockRecorder) ApproveOrder(ctx, userID, shopOrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveOrder", reflect.TypeOf((*MockOrderUsecase)(nil).ApproveOrder), ctx, userID, shopOrderID)
}

// CancelShopOrder mocks base method.
func (m *MockOrderUsecase) CancelShopOrder(ctx context.Context, userID, shopOrderID uuid.UUID, req entity.CancelOrderRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelShopOrder", ctx, userID, shopOrderID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelShopOrder indicates an expected call of CancelShopOrder.
func (mr *MockOrderUsecaseMockRecorder) CancelShopOrder(ctx, userID, shopOrderID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelShopOrder", reflect.TypeOf((*MockOrderUsecase)(nil).CancelShopOrder), ctx, userID, shopOrderID, req)
}

// CreateOrderFromCart mocks base method.
func (m *MockOrderUsecase) CreateOrderFromCart(ctx context.Context, userID uuid.UUID, req entity.CreateOrderRequest) (*entity.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderFromCart", ctx, userID, req)
	ret0, _ := ret[0].(*entity.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderFromCart indicates an expected call of CreateOrderFromCart.
func (mr *MockOrderUsecaseMockRecorder) CreateOrderFromCart(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderFromCart", reflect.TypeOf((*MockOrderUsecase)(nil).CreateOrderFromCart), ctx, userID, req)
}

// CreateOrderPayment mocks base method.
func (m *MockOrderUsecase) CreateOrderPayment(ctx context.Context, userID, orderID uuid.UUID, req entity.CreatePaymentRequest) (*entity.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderPayment", ctx, userID, orderID, req)
	ret0, _ := ret[0].(*entity.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderPayment indicates an expected call of CreateOrderPayment.
func (mr *MockOrderUsecaseMockRecorder) CreateOrderPayment(ctx, userID, orderID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderPayment", reflect.TypeOf((*MockOrderUsecase)(nil).CreateOrderPayment), ctx, userID, orderID, req)
}

// GetOrder mocks base method.
func (m *MockOrderUsecase) GetOrder(ctx context.Context, userID, shopOrderID uuid.UUID) (*entity.OrderListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, userID, shopOrderID)
	ret0, _ := ret[0].(*entity.OrderListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrderUsecaseMockRecorder) GetOrder(ctx, userID, shopOrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrderUsecase)(nil).GetOrder), ctx, userID, shopOrderID)
}

// GetOrderGroup mocks base method.
func (m *MockOrderUsecase) GetOrderGroup(ctx context.Context, userID, orderID uuid.UUID) (*entity.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderGroup", ctx, userID, orderID)
	ret0, _ := ret[0].(*entity.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderGroup indicates an expected call of GetOrderGroup.
func (mr *MockOrderUsecaseMockRecorder) GetOrderGroup(ctx, userID, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderGroup", reflect.TypeOf((*MockOrderUsecase)(nil).GetOrderGroup), ctx, userID, orderID)
}

// GetShipmentTracking mocks base method.
func (m *MockOrderUsecase) GetShipmentTracking(ctx context.Context, userID, shopOrderID uuid.UUID) (*entity.ShipmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShipmentTracking", ctx, userID, shopOrderID)
	ret0, _ := ret[0].(*entity.ShipmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShipmentTracking indicates an expected call of GetShipmentTracking.
func (mr *MockOrderUsecaseMockRecorder) GetShipmentTracking(ctx, userID, shopOrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShipmentTracking", reflect.TypeOf((*MockOrderUsecase)(nil).GetShipmentTracking), ctx, userID, shopOrderID)
}

// GetShopOrder mocks base method.
func (m *MockOrderUsecase) GetShopOrder(ctx context.Context, userID, shopOrderID uuid.UUID) (*entity.ShopOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopOrder", ctx, userID, shopOrderID)
	ret0, _ := ret[0].(*entity.ShopOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopOrder indicates an expected call of GetShopOrder.
func (mr *MockOrderUsecaseMockRecorder) GetShopOrder(ctx, userID, shopOrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopOrder", reflect.TypeOf((*MockOrderUsecase)(nil).GetShopOrder), ctx, userID, shopOrderID)
}

// ListOrderGroups mocks base method.
func (m *MockOrderUsecase) ListOrderGroups(ctx context.Context, userID uuid.UUID, req entity.OrderListRequest) (*entity.OrderGroupListPaginationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrderGroups", ctx, userID, req)
	ret0, _ := ret[0].(*entity.OrderGroupListPaginationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrderGroups indicates an expected call of ListOrderGroups.
func (mr *MockOrderUsecaseMockRecorder) ListOrderGroups(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrderGroups", reflect.TypeOf((*MockOrderUsecase)(nil).ListOrderGroups), ctx, userID, req)
}

// ListOrders mocks base method.
func (m *MockOrderUsecase) ListOrders(ctx context.Context, userID uuid.UUID, req entity.OrderListRequest) (*entity.OrderListPaginationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", ctx, userID, req)
	ret0, _ := ret[0].(*entity.OrderListPaginationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockOrderUsecaseMockRecorder) ListOrders(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockOrderUsecase)(nil).ListOrders), ctx, userID, req)
}

// ListShopOrders mocks base method.
func (m *MockOrderUsecase) ListShopOrders(ctx context.Context, userID uuid.UUID, req entity.OrderListRequest) (*entity.ShopOrderListPaginationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShopOrders", ctx, userID, req)
	ret0, _ := ret[0].(*entity.ShopOrderListPaginationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShopOrders indicates an expected call of ListShopOrders.
func (mr *MockOrderUsecaseMockRecorder) ListShopOrders(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShopOrders", reflect.TypeOf((*MockOrderUsecase)(nil).ListShopOrders), ctx, userID, req)
}

// UpdateShopOrderStatus mocks base method.
func (m *MockOrderUsecase) UpdateShopOrderStatus(ctx context.Context, userID, shopOrderID uuid.UUID, req entity.UpdateOrderStatusRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShopOrderStatus", ctx, userID, shopOrderID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateShopOrderStatus indicates an expected call of UpdateShopOrderStatus.
func (mr *MockOrderUsecaseMockRecorder) UpdateShopOrderStatus(ctx, userID, shopOrderID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShopOrderStatus", reflect.TypeOf((*MockOrderUsecase)(nil).UpdateShopOrderStatus), ctx, userID, shopOrderID, req)
}

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// AddCartItem mocks base method.
func (m *MockOrderRepository) AddCartItem(ctx context.Context, item *entity.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCartItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCartItem indicates an expected call of AddCartItem.
func (mr *MockOrderRepositoryMockRecorder) AddCartItem(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCartItem", reflect.TypeOf((*MockOrderRepository)(nil).AddCartItem), ctx, item)
}

// AddShipment mocks base method.
func (m *MockOrderRepository) AddShipment(ctx context.Context, s *entity.Shipment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddShipment", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddShipment indicates an expected call of AddShipment.
func (mr *MockOrderRepositoryMockRecorder) AddShipment(ctx, s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddShipment", reflect.TypeOf((*MockOrderRepository)(nil).AddShipment), ctx, s)
}

// CancelShopOrder mocks base method.
func (m *MockOrderRepository) CancelShopOrder(ctx context.Context, id uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelShopOrder", ctx, id, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelShopOrder indicates an expected call of CancelShopOrder.
func (mr *MockOrderRepositoryMockRecorder) CancelShopOrder(ctx, id, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelShopOrder", reflect.TypeOf((*MockOrderRepository)(nil).CancelShopOrder), ctx, id, reason)
}

// ClearCart mocks base method.
func (m *MockOrderRepository) ClearCart(ctx context.Context, cartID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCart", ctx, cartID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCart indicates an expected call of ClearCart.
func (mr *MockOrderRepositoryMockRecorder) ClearCart(ctx, cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCart", reflect.TypeOf((*MockOrderRepository)(nil).ClearCart), ctx, cartID)
}

// CreateFullOrder mocks base method.
func (m *MockOrderRepository) CreateFullOrder(ctx context.Context, order *entity.Order, shopOrders []*entity.ShopOrder, orderItemsByShop map[string][]*entity.OrderItem, payment *entity.Payment, cartID int, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFullOrder", ctx, order, shopOrders, orderItemsByShop, payment, cartID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFullOrder indicates an expected call of CreateFullOrder.
func (mr *MockOrderRepositoryMockRecorder) CreateFullOrder(ctx, order, shopOrders, orderItemsByShop, payment, cartID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFullOrder", reflect.TypeOf((*MockOrderRepository)(nil).CreateFullOrder), ctx, order, shopOrders, orderItemsByShop, payment, cartID, userID)
}

// CreateOrder mocks base method.
func (m *MockOrderRepository) CreateOrder(ctx context.Context, order *entity.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderRepositoryMockRecorder) CreateOrder(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderRepository)(nil).CreateOrder), ctx, order)
}

// CreateOrderItems mocks base method.
func (m *MockOrderRepository) CreateOrderItems(ctx context.Context, items []*entity.OrderItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderItems", ctx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrderItems indicates an expected call of CreateOrderItems.
func (mr *MockOrderRepositoryMockRecorder) CreateOrderItems(ctx, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderItems", reflect.TypeOf((*MockOrderRepository)(nil).CreateOrderItems), ctx, items)
}

// CreateOrderLog mocks base method.
func (m *MockOrderRepository) CreateOrderLog(ctx context.Context, log *entity.OrderLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderLog", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrderLog indicates an expected call of CreateOrderLog.
func (mr *MockOrderRepositoryMockRecorder) CreateOrderLog(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderLog", reflect.TypeOf((*MockOrderRepository)(nil).CreateOrderLog), ctx, log)
}

// CreatePayment mocks base method.
func (m *MockOrderRepository) CreatePayment(ctx context.Context, payment *entity.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockOrderRepositoryMockRecorder) CreatePayment(ctx, payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockOrderRepository)(nil).CreatePayment), ctx, payment)
}

// CreateShopOrder mocks base method.
func (m *MockOrderRepository) CreateShopOrder(ctx context.Context, so *entity.ShopOrder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShopOrder", ctx, so)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateShopOrder indicates an expected call of CreateShopOrder.
func (mr *MockOrderRepositoryMockRecorder) CreateShopOrder(ctx, so interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShopOrder", reflect.TypeOf((*MockOrderRepository)(nil).CreateShopOrder), ctx, so)
}

// EnsureCartForUser mocks base method.
func (m *MockOrderRepository) EnsureCartForUser(ctx context.Context, userID uuid.UUID) (*entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureCartForUser", ctx, userID)
	ret0, _ := ret[0].(*entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureCartForUser indicates an expected call of EnsureCartForUser.
func (mr *MockOrderRepositoryMockRecorder) EnsureCartForUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureCartForUser", reflect.TypeOf((*MockOrderRepository)(nil).EnsureCartForUser), ctx, userID)
}

// GetCartByUserID mocks base method.
func (m *MockOrderRepository) GetCartByUserID(ctx context.Context, userID uuid.UUID) (*entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartByUserID indicates an expected call of GetCartByUserID.
func (mr *MockOrderRepositoryMockRecorder) GetCartByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartByUserID", reflect.TypeOf((*MockOrderRepository)(nil).GetCartByUserID), ctx, userID)
}

// GetCartItemByID mocks base method.
func (m *MockOrderRepository) GetCartItemByID(ctx context.Context, id int) (*entity.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItemByID", ctx, id)
	ret0, _ := ret[0].(*entity.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartItemByID indicates an expected call of GetCartItemByID.
func (mr *MockOrderRepositoryMockRecorder) GetCartItemByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItemByID", reflect.TypeOf((*MockOrderRepository)(nil).GetCartItemByID), ctx, id)
}

// GetOrderByID mocks base method.
func (m *MockOrderRepository) GetOrderByID(ctx context.Context, id uuid.UUID) (*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, id)
	ret0, _ := ret[0].(*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrderRepositoryMockRecorder) GetOrderByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrderRepository)(nil).GetOrderByID), ctx, id)
}

// GetOrderLogsByOrderID mocks base method.
func (m *MockOrderRepository) GetOrderLogsByOrderID(ctx context.Context, orderID uuid.UUID) ([]*entity.OrderLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderLogsByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]*entity.OrderLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderLogsByOrderID indicates an expected call of GetOrderLogsByOrderID.
func (mr *MockOrderRepositoryMockRecorder) GetOrderLogsByOrderID(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderLogsByOrderID", reflect.TypeOf((*MockOrderRepository)(nil).GetOrderLogsByOrderID), ctx, orderID)
}

// GetOrderLogsByShopOrderID mocks base method.
func (m *MockOrderRepository) GetOrderLogsByShopOrderID(ctx context.Context, shopOrderID uuid.UUID) ([]*entity.OrderLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderLogsByShopOrderID", ctx, shopOrderID)
	ret0, _ := ret[0].([]*entity.OrderLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderLogsByShopOrderID indicates an expected call of GetOrderLogsByShopOrderID.
func (mr *MockOrderRepositoryMockRecorder) GetOrderLogsByShopOrderID(ctx, shopOrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderLogsByShopOrderID", reflect.TypeOf((*MockOrderRepository)(nil).GetOrderLogsByShopOrderID), ctx, shopOrderID)
}

// GetPaymentByOrderID mocks base method.
func (m *MockOrderRepository) GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByOrderID indicates an expected call of GetPaymentByOrderID.
func (mr *MockOrderRepositoryMockRecorder) GetPaymentByOrderID(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByOrderID", reflect.TypeOf((*MockOrderRepository)(nil).GetPaymentByOrderID), ctx, orderID)
}

// GetPaymentByTransactionID mocks base method.
func (m *MockOrderRepository) GetPaymentByTransactionID(ctx context.Context, transactionID string) (*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].(*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByTransactionID indicates an expected call of GetPaymentByTransactionID.
func (mr *MockOrderRepositoryMockRecorder) GetPaymentByTransactionID(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByTransactionID", reflect.TypeOf((*MockOrderRepository)(nil).GetPaymentByTransactionID), ctx, transactionID)
}

// GetShipmentByShopOrderID mocks base method.
func (m *MockOrderRepository) GetShipmentByShopOrderID(ctx context.Context, shopOrderID uuid.UUID) (*entity.Shipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShipmentByShopOrderID", ctx, shopOrderID)
	ret0, _ := ret[0].(*entity.Shipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShipmentByShopOrderID indicates an expected call of GetShipmentByShopOrderID.
func (mr *MockOrderRepositoryMockRecorder) GetShipmentByShopOrderID(ctx, shopOrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShipmentByShopOrderID", reflect.TypeOf((*MockOrderRepository)(nil).GetShipmentByShopOrderID), ctx, shopOrderID)
}

// GetShopOrderByID mocks base method.
func (m *MockOrderRepository) GetShopOrderByID(ctx context.Context, id uuid.UUID) (*entity.ShopOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopOrderByID", ctx, id)
	ret0, _ := ret[0].(*entity.ShopOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopOrderByID indicates an expected call of GetShopOrderByID.
func (mr *MockOrderRepositoryMockRecorder) GetShopOrderByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopOrderByID", reflect.TypeOf((*MockOrderRepository)(nil).GetShopOrderByID), ctx, id)
}

// ListCartItems mocks base method.
func (m *MockOrderRepository) ListCartItems(ctx context.Context, cartID int) ([]*entity.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCartItems", ctx, cartID)
	ret0, _ := ret[0].([]*entity.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCartItems indicates an expected call of ListCartItems.
func (mr *MockOrderRepositoryMockRecorder) ListCartItems(ctx, cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCartItems", reflect.TypeOf((*MockOrderRepository)(nil).ListCartItems), ctx, cartID)
}

// ListDeliveredOrdersOlderThan mocks base method.
func (m *MockOrderRepository) ListDeliveredOrdersOlderThan(ctx context.Context, days int) ([]*entity.ShopOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeliveredOrdersOlderThan", ctx, days)
	ret0, _ := ret[0].([]*entity.ShopOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeliveredOrdersOlderThan indicates an expected call of ListDeliveredOrdersOlderThan.
func (mr *MockOrderRepositoryMockRecorder) ListDeliveredOrdersOlderThan(ctx, days interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeliveredOrdersOlderThan", reflect.TypeOf((*MockOrderRepository)(nil).ListDeliveredOrdersOlderThan), ctx, days)
}

// ListExpiredPayments mocks base method.
func (m *MockOrderRepository) ListExpiredPayments(ctx context.Context) ([]*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredPayments", ctx)
	ret0, _ := ret[0].([]*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredPayments indicates an expected call of ListExpiredPayments.
func (mr *MockOrderRepositoryMockRecorder) ListExpiredPayments(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredPayments", reflect.TypeOf((*MockOrderRepository)(nil).ListExpiredPayments), ctx)
}

// ListOrdersByUser mocks base method.
func (m *MockOrderRepository) ListOrdersByUser(ctx context.Context, userID uuid.UUID, req entity.OrderListRequest) ([]*entity.Order, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrdersByUser", ctx, userID, req)
	ret0, _ := ret[0].([]*entity.Order)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOrdersByUser indicates an expected call of ListOrdersByUser.
func (mr *MockOrderRepositoryMockRecorder) ListOrdersByUser(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrdersByUser", reflect.TypeOf((*MockOrderRepository)(nil).ListOrdersByUser), ctx, userID, req)
}

// ListShopOrdersByShopID mocks base method.
func (m *MockOrderRepository) ListShopOrdersByShopID(ctx context.Context, shopID uuid.UUID, req entity.OrderListRequest) ([]*entity.ShopOrder, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShopOrdersByShopID", ctx, shopID, req)
	ret0, _ := ret[0].([]*entity.ShopOrder)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListShopOrdersByShopID indicates an expected call of ListShopOrdersByShopID.
func (mr *MockOrderRepositoryMockRecorder) ListShopOrdersByShopID(ctx, shopID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShopOrdersByShopID", reflect.TypeOf((*MockOrderRepository)(nil).ListShopOrdersByShopID), ctx, shopID, req)
}

// ListShopOrdersByUserID mocks base method.
func (m *MockOrderRepository) ListShopOrdersByUserID(ctx context.Context, userID uuid.UUID, req entity.OrderListRequest) ([]*entity.ShopOrder, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShopOrdersByUserID", ctx, userID, req)
	ret0, _ := ret[0].([]*entity.ShopOrder)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListShopOrdersByUserID indicates an expected call of ListShopOrdersByUserID.
func (mr *MockOrderRepositoryMockRecorder) ListShopOrdersByUserID(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShopOrdersByUserID", reflect.TypeOf((*MockOrderRepository)(nil).ListShopOrdersByUserID), ctx, userID, req)
}

// UpdatePaymentStatus mocks base method.
func (m *MockOrderRepository) UpdatePaymentStatus(ctx context.Context, id uuid.UUID, paymentStatusID int, paidAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentStatus", ctx, id, paymentStatusID, paidAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentStatus indicates an expected call of UpdatePaymentStatus.
func (mr *MockOrderRepositoryMockRecorder) UpdatePaymentStatus(ctx, id, paymentStatusID, paidAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentStatus", reflect.TypeOf((*MockOrderRepository)(nil).UpdatePaymentStatus), ctx, id, paymentStatusID, paidAt)
}

// UpdateShipmentStatusByShopOrderID mocks base method.
func (m *MockOrderRepository) UpdateShipmentStatusByShopOrderID(ctx context.Context, shopOrderID uuid.UUID, shipmentStatusID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShipmentStatusByShopOrderID", ctx, shopOrderID, shipmentStatusID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateShipmentStatusByShopOrderID indicates an expected call of UpdateShipmentStatusByShopOrderID.
func (mr *MockOrderRepositoryMockRecorder) UpdateShipmentStatusByShopOrderID(ctx, shopOrderID, shipmentStatusID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShipmentStatusByShopOrderID", reflect.TypeOf((*MockOrderRepository)(nil).UpdateShipmentStatusByShopOrderID), ctx, shopOrderID, shipmentStatusID)
}

// UpdateShopOrderStatus mocks base method.
func (m *MockOrderRepository) UpdateShopOrderStatus(ctx context.Context, id uuid.UUID, OrderStatusID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShopOrderStatus", ctx, id, OrderStatusID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateShopOrderStatus indicates an expected call of UpdateShopOrderStatus.
func (mr *MockOrderRepositoryMockRecorder) UpdateShopOrderStatus(ctx, id, OrderStatusID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShopOrderStatus", reflect.TypeOf((*MockOrderRepository)(nil).UpdateShopOrderStatus), ctx, id, OrderStatusID)
}

// UpsertCartItem mocks base method.
func (m *MockOrderRepository) UpsertCartItem(ctx context.Context, item *entity.CartItem) (*entity.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCartItem", ctx, item)
	ret0, _ := ret[0].(*entity.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCartItem indicates an expected call of UpsertCartItem.
func (mr *MockOrderRepositoryMockRecorder) UpsertCartItem(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCartItem", reflect.TypeOf((*MockOrderRepository)(nil).UpsertCartItem), ctx, item)
}
