// Code generated by MockGen. DO NOT EDIT.
// Source: domain/shop.go
//
// Generated by this command:
//
//	mockgen -source=domain/shop.go -destination=domain/mock/mock_shop.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	entity "ecommerce-go-api/entity"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockShopUsecase is a mock of ShopUsecase interface.
type MockShopUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockShopUsecaseMockRecorder
	isgomock struct{}
}

// MockShopUsecaseMockRecorder is the mock recorder for MockShopUsecase.
type MockShopUsecaseMockRecorder struct {
	mock *MockShopUsecase
}

// NewMockShopUsecase creates a new mock instance.
func NewMockShopUsecase(ctrl *gomock.Controller) *MockShopUsecase {
	mock := &MockShopUsecase{ctrl: ctrl}
	mock.recorder = &MockShopUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopUsecase) EXPECT() *MockShopUsecaseMockRecorder {
	return m.recorder
}

// ActivateShop mocks base method.
func (m *MockShopUsecase) ActivateShop(ctx context.Context, shopID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateShop", ctx, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateShop indicates an expected call of ActivateShop.
func (mr *MockShopUsecaseMockRecorder) ActivateShop(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateShop", reflect.TypeOf((*MockShopUsecase)(nil).ActivateShop), ctx, shopID)
}

// DeactivateShop mocks base method.
func (m *MockShopUsecase) DeactivateShop(ctx context.Context, shopID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateShop", ctx, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateShop indicates an expected call of DeactivateShop.
func (mr *MockShopUsecaseMockRecorder) DeactivateShop(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateShop", reflect.TypeOf((*MockShopUsecase)(nil).DeactivateShop), ctx, shopID)
}

// GetShopByID mocks base method.
func (m *MockShopUsecase) GetShopByID(ctx context.Context, shopID uuid.UUID) (*entity.ShopResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopByID", ctx, shopID)
	ret0, _ := ret[0].(*entity.ShopResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopByID indicates an expected call of GetShopByID.
func (mr *MockShopUsecaseMockRecorder) GetShopByID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopByID", reflect.TypeOf((*MockShopUsecase)(nil).GetShopByID), ctx, shopID)
}

// GetShopByUserID mocks base method.
func (m *MockShopUsecase) GetShopByUserID(ctx context.Context, userID uuid.UUID) (*entity.ShopResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.ShopResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopByUserID indicates an expected call of GetShopByUserID.
func (mr *MockShopUsecaseMockRecorder) GetShopByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopByUserID", reflect.TypeOf((*MockShopUsecase)(nil).GetShopByUserID), ctx, userID)
}

// GetShopCouriers mocks base method.
func (m *MockShopUsecase) GetShopCouriers(ctx context.Context, userID uuid.UUID) (*entity.ShopCourierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopCouriers", ctx, userID)
	ret0, _ := ret[0].(*entity.ShopCourierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopCouriers indicates an expected call of GetShopCouriers.
func (mr *MockShopUsecaseMockRecorder) GetShopCouriers(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopCouriers", reflect.TypeOf((*MockShopUsecase)(nil).GetShopCouriers), ctx, userID)
}

// ListShops mocks base method.
func (m *MockShopUsecase) ListShops(ctx context.Context, req *entity.ShopListRequest) (*entity.ShopListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShops", ctx, req)
	ret0, _ := ret[0].(*entity.ShopListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShops indicates an expected call of ListShops.
func (mr *MockShopUsecaseMockRecorder) ListShops(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShops", reflect.TypeOf((*MockShopUsecase)(nil).ListShops), ctx, req)
}

// UpdateShop mocks base method.
func (m *MockShopUsecase) UpdateShop(ctx context.Context, shopID, userID uuid.UUID, req *entity.UpdateShopRequest) (*entity.ShopResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShop", ctx, shopID, userID, req)
	ret0, _ := ret[0].(*entity.ShopResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateShop indicates an expected call of UpdateShop.
func (mr *MockShopUsecaseMockRecorder) UpdateShop(ctx, shopID, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShop", reflect.TypeOf((*MockShopUsecase)(nil).UpdateShop), ctx, shopID, userID, req)
}

// UpdateShopCouriers mocks base method.
func (m *MockShopUsecase) UpdateShopCouriers(ctx context.Context, userID uuid.UUID, req *entity.UpdateShopCouriersRequest) (*entity.ShopCourierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShopCouriers", ctx, userID, req)
	ret0, _ := ret[0].(*entity.ShopCourierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateShopCouriers indicates an expected call of UpdateShopCouriers.
func (mr *MockShopUsecaseMockRecorder) UpdateShopCouriers(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShopCouriers", reflect.TypeOf((*MockShopUsecase)(nil).UpdateShopCouriers), ctx, userID, req)
}

// MockShopRepository is a mock of ShopRepository interface.
type MockShopRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShopRepositoryMockRecorder
	isgomock struct{}
}

// MockShopRepositoryMockRecorder is the mock recorder for MockShopRepository.
type MockShopRepositoryMockRecorder struct {
	mock *MockShopRepository
}

// NewMockShopRepository creates a new mock instance.
func NewMockShopRepository(ctrl *gomock.Controller) *MockShopRepository {
	mock := &MockShopRepository{ctrl: ctrl}
	mock.recorder = &MockShopRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopRepository) EXPECT() *MockShopRepositoryMockRecorder {
	return m.recorder
}

// CreateShopCourier mocks base method.
func (m *MockShopRepository) CreateShopCourier(ctx context.Context, courier *entity.ShopCourier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShopCourier", ctx, courier)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateShopCourier indicates an expected call of CreateShopCourier.
func (mr *MockShopRepositoryMockRecorder) CreateShopCourier(ctx, courier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShopCourier", reflect.TypeOf((*MockShopRepository)(nil).CreateShopCourier), ctx, courier)
}

// GetActiveShopCourier mocks base method.
func (m *MockShopRepository) GetActiveShopCourier(ctx context.Context, shopID uuid.UUID) (*entity.ShopCourier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveShopCourier", ctx, shopID)
	ret0, _ := ret[0].(*entity.ShopCourier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveShopCourier indicates an expected call of GetActiveShopCourier.
func (mr *MockShopRepositoryMockRecorder) GetActiveShopCourier(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveShopCourier", reflect.TypeOf((*MockShopRepository)(nil).GetActiveShopCourier), ctx, shopID)
}

// GetShopByID mocks base method.
func (m *MockShopRepository) GetShopByID(ctx context.Context, id uuid.UUID) (*entity.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopByID", ctx, id)
	ret0, _ := ret[0].(*entity.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopByID indicates an expected call of GetShopByID.
func (mr *MockShopRepositoryMockRecorder) GetShopByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopByID", reflect.TypeOf((*MockShopRepository)(nil).GetShopByID), ctx, id)
}

// GetShopByUserID mocks base method.
func (m *MockShopRepository) GetShopByUserID(ctx context.Context, userID uuid.UUID) (*entity.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopByUserID indicates an expected call of GetShopByUserID.
func (mr *MockShopRepositoryMockRecorder) GetShopByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopByUserID", reflect.TypeOf((*MockShopRepository)(nil).GetShopByUserID), ctx, userID)
}

// GetShopsByIDs mocks base method.
func (m *MockShopRepository) GetShopsByIDs(ctx context.Context, ids []uuid.UUID) ([]*entity.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopsByIDs", ctx, ids)
	ret0, _ := ret[0].([]*entity.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopsByIDs indicates an expected call of GetShopsByIDs.
func (mr *MockShopRepositoryMockRecorder) GetShopsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopsByIDs", reflect.TypeOf((*MockShopRepository)(nil).GetShopsByIDs), ctx, ids)
}

// ListShopCouriersByShopIDs mocks base method.
func (m *MockShopRepository) ListShopCouriersByShopIDs(ctx context.Context, shopIDs []uuid.UUID) ([]*entity.ShopCourier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShopCouriersByShopIDs", ctx, shopIDs)
	ret0, _ := ret[0].([]*entity.ShopCourier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShopCouriersByShopIDs indicates an expected call of ListShopCouriersByShopIDs.
func (mr *MockShopRepositoryMockRecorder) ListShopCouriersByShopIDs(ctx, shopIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShopCouriersByShopIDs", reflect.TypeOf((*MockShopRepository)(nil).ListShopCouriersByShopIDs), ctx, shopIDs)
}

// ListShops mocks base method.
func (m *MockShopRepository) ListShops(ctx context.Context, req *entity.ShopListRequest) ([]*entity.Shop, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShops", ctx, req)
	ret0, _ := ret[0].([]*entity.Shop)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListShops indicates an expected call of ListShops.
func (mr *MockShopRepositoryMockRecorder) ListShops(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShops", reflect.TypeOf((*MockShopRepository)(nil).ListShops), ctx, req)
}

// SoftDeleteShopCouriers mocks base method.
func (m *MockShopRepository) SoftDeleteShopCouriers(ctx context.Context, shopID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteShopCouriers", ctx, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteShopCouriers indicates an expected call of SoftDeleteShopCouriers.
func (mr *MockShopRepositoryMockRecorder) SoftDeleteShopCouriers(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteShopCouriers", reflect.TypeOf((*MockShopRepository)(nil).SoftDeleteShopCouriers), ctx, shopID)
}

// UpdateShop mocks base method.
func (m *MockShopRepository) UpdateShop(ctx context.Context, shop *entity.Shop) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShop", ctx, shop)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateShop indicates an expected call of UpdateShop.
func (mr *MockShopRepositoryMockRecorder) UpdateShop(ctx, shop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShop", reflect.TypeOf((*MockShopRepository)(nil).UpdateShop), ctx, shop)
}

// UpdateStatus mocks base method.
func (m *MockShopRepository) UpdateStatus(ctx context.Context, id uuid.UUID, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockShopRepositoryMockRecorder) UpdateStatus(ctx, id, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockShopRepository)(nil).UpdateStatus), ctx, id, isActive)
}
