// Code generated by MockGen. DO NOT EDIT.
// Source: domain/cart.go
//
// Generated by this command:
//
//	mockgen -source=domain/cart.go -destination=domain/mock/mock_cart.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	entity "ecommerce-go-api/entity"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCartUsecase is a mock of CartUsecase interface.
type MockCartUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCartUsecaseMockRecorder
	isgomock struct{}
}

// MockCartUsecaseMockRecorder is the mock recorder for MockCartUsecase.
type MockCartUsecaseMockRecorder struct {
	mock *MockCartUsecase
}

// NewMockCartUsecase creates a new mock instance.
func NewMockCartUsecase(ctrl *gomock.Controller) *MockCartUsecase {
	mock := &MockCartUsecase{ctrl: ctrl}
	mock.recorder = &MockCartUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartUsecase) EXPECT() *MockCartUsecaseMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockCartUsecase) AddItem(ctx context.Context, userID uuid.UUID, productID, qty uint32) (*entity.CartItem, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, userID, productID, qty)
	ret0, _ := ret[0].(*entity.CartItem)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddItem indicates an expected call of AddItem.
func (mr *MockCartUsecaseMockRecorder) AddItem(ctx, userID, productID, qty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockCartUsecase)(nil).AddItem), ctx, userID, productID, qty)
}

// DeleteItem mocks base method.
func (m *MockCartUsecase) DeleteItem(ctx context.Context, userID uuid.UUID, itemID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, userID, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockCartUsecaseMockRecorder) DeleteItem(ctx, userID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockCartUsecase)(nil).DeleteItem), ctx, userID, itemID)
}

// EstimateShipping mocks base method.
func (m *MockCartUsecase) EstimateShipping(ctx context.Context, userID uuid.UUID, cartItemIDs []uint32) (*entity.CartShippingEstimateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateShipping", ctx, userID, cartItemIDs)
	ret0, _ := ret[0].(*entity.CartShippingEstimateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateShipping indicates an expected call of EstimateShipping.
func (mr *MockCartUsecaseMockRecorder) EstimateShipping(ctx, userID, cartItemIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateShipping", reflect.TypeOf((*MockCartUsecase)(nil).EstimateShipping), ctx, userID, cartItemIDs)
}

// GetCart mocks base method.
func (m *MockCartUsecase) GetCart(ctx context.Context, userID uuid.UUID) (*entity.Cart, []*entity.CartItem, *entity.CartSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", ctx, userID)
	ret0, _ := ret[0].(*entity.Cart)
	ret1, _ := ret[1].([]*entity.CartItem)
	ret2, _ := ret[2].(*entity.CartSummary)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetCart indicates an expected call of GetCart.
func (mr *MockCartUsecaseMockRecorder) GetCart(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockCartUsecase)(nil).GetCart), ctx, userID)
}

// UpdateItem mocks base method.
func (m *MockCartUsecase) UpdateItem(ctx context.Context, userID uuid.UUID, itemID, qty uint32) (*entity.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, userID, itemID, qty)
	ret0, _ := ret[0].(*entity.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockCartUsecaseMockRecorder) UpdateItem(ctx, userID, itemID, qty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockCartUsecase)(nil).UpdateItem), ctx, userID, itemID, qty)
}

// MockCartRepository is a mock of CartRepository interface.
type MockCartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepositoryMockRecorder
	isgomock struct{}
}

// MockCartRepositoryMockRecorder is the mock recorder for MockCartRepository.
type MockCartRepositoryMockRecorder struct {
	mock *MockCartRepository
}

// NewMockCartRepository creates a new mock instance.
func NewMockCartRepository(ctrl *gomock.Controller) *MockCartRepository {
	mock := &MockCartRepository{ctrl: ctrl}
	mock.recorder = &MockCartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepository) EXPECT() *MockCartRepositoryMockRecorder {
	return m.recorder
}

// AddCartItem mocks base method.
func (m *MockCartRepository) AddCartItem(ctx context.Context, item *entity.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCartItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCartItem indicates an expected call of AddCartItem.
func (mr *MockCartRepositoryMockRecorder) AddCartItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCartItem", reflect.TypeOf((*MockCartRepository)(nil).AddCartItem), ctx, item)
}

// ClearCart mocks base method.
func (m *MockCartRepository) ClearCart(ctx context.Context, cartID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCart", ctx, cartID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCart indicates an expected call of ClearCart.
func (mr *MockCartRepositoryMockRecorder) ClearCart(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCart", reflect.TypeOf((*MockCartRepository)(nil).ClearCart), ctx, cartID)
}

// DeleteCartItem mocks base method.
func (m *MockCartRepository) DeleteCartItem(ctx context.Context, id uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartItem", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCartItem indicates an expected call of DeleteCartItem.
func (mr *MockCartRepositoryMockRecorder) DeleteCartItem(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartItem", reflect.TypeOf((*MockCartRepository)(nil).DeleteCartItem), ctx, id)
}

// EnsureCartForUser mocks base method.
func (m *MockCartRepository) EnsureCartForUser(ctx context.Context, userID uuid.UUID) (*entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureCartForUser", ctx, userID)
	ret0, _ := ret[0].(*entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureCartForUser indicates an expected call of EnsureCartForUser.
func (mr *MockCartRepositoryMockRecorder) EnsureCartForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureCartForUser", reflect.TypeOf((*MockCartRepository)(nil).EnsureCartForUser), ctx, userID)
}

// GetCartByUserID mocks base method.
func (m *MockCartRepository) GetCartByUserID(ctx context.Context, userID uuid.UUID) (*entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartByUserID indicates an expected call of GetCartByUserID.
func (mr *MockCartRepositoryMockRecorder) GetCartByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartByUserID", reflect.TypeOf((*MockCartRepository)(nil).GetCartByUserID), ctx, userID)
}

// GetCartItemByCartAndProduct mocks base method.
func (m *MockCartRepository) GetCartItemByCartAndProduct(ctx context.Context, cartID, productID uint32) (*entity.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItemByCartAndProduct", ctx, cartID, productID)
	ret0, _ := ret[0].(*entity.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartItemByCartAndProduct indicates an expected call of GetCartItemByCartAndProduct.
func (mr *MockCartRepositoryMockRecorder) GetCartItemByCartAndProduct(ctx, cartID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItemByCartAndProduct", reflect.TypeOf((*MockCartRepository)(nil).GetCartItemByCartAndProduct), ctx, cartID, productID)
}

// GetCartItemByID mocks base method.
func (m *MockCartRepository) GetCartItemByID(ctx context.Context, id uint32) (*entity.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItemByID", ctx, id)
	ret0, _ := ret[0].(*entity.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartItemByID indicates an expected call of GetCartItemByID.
func (mr *MockCartRepositoryMockRecorder) GetCartItemByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItemByID", reflect.TypeOf((*MockCartRepository)(nil).GetCartItemByID), ctx, id)
}

// GetCartItemByUserAndProduct mocks base method.
func (m *MockCartRepository) GetCartItemByUserAndProduct(ctx context.Context, userID uuid.UUID, productID uint32) (*entity.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItemByUserAndProduct", ctx, userID, productID)
	ret0, _ := ret[0].(*entity.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartItemByUserAndProduct indicates an expected call of GetCartItemByUserAndProduct.
func (mr *MockCartRepositoryMockRecorder) GetCartItemByUserAndProduct(ctx, userID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItemByUserAndProduct", reflect.TypeOf((*MockCartRepository)(nil).GetCartItemByUserAndProduct), ctx, userID, productID)
}

// GetCartItemsByIDs mocks base method.
func (m *MockCartRepository) GetCartItemsByIDs(ctx context.Context, ids []uint32) ([]*entity.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItemsByIDs", ctx, ids)
	ret0, _ := ret[0].([]*entity.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartItemsByIDs indicates an expected call of GetCartItemsByIDs.
func (mr *MockCartRepositoryMockRecorder) GetCartItemsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItemsByIDs", reflect.TypeOf((*MockCartRepository)(nil).GetCartItemsByIDs), ctx, ids)
}

// ListCartItems mocks base method.
func (m *MockCartRepository) ListCartItems(ctx context.Context, cartID uint32) ([]*entity.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCartItems", ctx, cartID)
	ret0, _ := ret[0].([]*entity.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCartItems indicates an expected call of ListCartItems.
func (mr *MockCartRepositoryMockRecorder) ListCartItems(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCartItems", reflect.TypeOf((*MockCartRepository)(nil).ListCartItems), ctx, cartID)
}

// UpdateCartItem mocks base method.
func (m *MockCartRepository) UpdateCartItem(ctx context.Context, item *entity.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCartItem indicates an expected call of UpdateCartItem.
func (mr *MockCartRepositoryMockRecorder) UpdateCartItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItem", reflect.TypeOf((*MockCartRepository)(nil).UpdateCartItem), ctx, item)
}

// UpsertCartItem mocks base method.
func (m *MockCartRepository) UpsertCartItem(ctx context.Context, item *entity.CartItem) (*entity.CartItem, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCartItem", ctx, item)
	ret0, _ := ret[0].(*entity.CartItem)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpsertCartItem indicates an expected call of UpsertCartItem.
func (mr *MockCartRepositoryMockRecorder) UpsertCartItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCartItem", reflect.TypeOf((*MockCartRepository)(nil).UpsertCartItem), ctx, item)
}
